name: Metrics
on:
  # Schedule weekly updates
  schedule: 
  - cron: "0 0 * * 0"
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

      - name: Topics
        uses: lowlighter/metrics@latest
        with:
          filename: topics.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          output_action: gist
          committer_gist: ${{ secrets.GIST }}


     
