name: Metrics
on:
  # Schedule weekly updates
  schedule: 
  - cron: "0 0 * * 0"
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
